version: '1.0'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: collabquiz
      POSTGRES_PASSWORD: collabquiz
      POSTGRES_DB: collabquiz
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
